language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.8

cache:
  directories:
    - $HOME/.cache/pip

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

matrix:
  exclude:
    - python: 3.4
      env: DJANGO=3.0
    - python: 3.4
      env: DJANGO=3.1

    - python: 3.5
      env: DJANGO=3.0
    - python: 3.5
      env: DJANGO=3.1

    - python: 3.6
      env: DJANGO=3.0
    - python: 3.6
      env: DJANGO=3.1


install:
  - pip install tox-travis "coverage<=4.0" codecov

script:
  - tox

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
